[devent]

# the name of the devent
name="IPFS Camp 2022"
seoDescription="IPFS Camp 2022 is a gathering for the entire IPFS community: devs, operators, implementers, researchers in Lisbon"

# where the event is happening
location="Convento do Beato, Lisbon, Portugal"

# the dates the devent runs
dateStart = "2022-10-28"
dateEnd = "2022-10-30"

# a pithy tag line you want to show in the "hero/splash" part of the landing page
tagline="""
IPFS Camp 2022  is a gathering for the entire  IPFS community: devs, operators, implementers,  researchers – and you!
"""

description="""
Join us for talks, workshops, discussion circles, hacking time, and more, all focused on celebrating and advancing IPFS. October 28-30, Lisbon, Portugal

Please reach out to camp@ipfs.io if you would like to sponsor IPFS Camp 2022.
"""


# a link to the devent website (what domain do you expect to use?) also used for canonical tag
link="https://2022.ipfs.camp/"

# a link to get tickets
ticketLink="#tickets"

# a link to RSVP for the event
# rsvpLink="#tickets"

# a link to apply to speak for the event
speakLink="https://airtable.com/shrOxmXUqwojf0Bjj"

# a link to the recap and videos
# recapLink="https://blog.ipfs.io/ipfs-ping-2022-recap/"

ogImage="/ipfs-camp-og.png"

# a link to a logo image for the event
logo="ipfs-camp-logo.svg"

# a link to a large res image for the hero/splash background.
# you likely want to use the devent location/city or something meaningful to the community
bgimg="tree-mandala.png"

# the organizers of the devent (usually a group)
org="the IPFS Project"

# the website of the organizers
orglink="https://ipfs.tech"

# url for this event repo
repo="https://github.com/pathfindertools/ipfs-camp-2022"

# Header Navigation
# [
#   ["Item 1", "#item1"],
#   ["Item 2", "#item2"],
# ]
navigation = [
  ["About", "./#about" ],
  ["Tracks", "./#tracks" ],
  ["Tickets", "./#tickets" ],
  ["Schedule", "./#schedule" ],
  ["Speakers", "./#speakers" ],
  ["FAQ", "./#faq" ],
]

# list the participating teams.
# the format here is:
# [
#   ["Team Name", "https://team.org", "https://team.org/team-logo.jpg"],
# ]
teams = [
  ["Protocol Labs", "https://protocol.ai", "https://media.graphassets.com/e8bIG2apSUauy2dqK35W" ],
  ["Consensus Lab", "http://consensus-lab.com/", "./teams/consensus-lab.png" ],
  ["Filecoin Foundation", "https://fil.org/", "./teams/filecoin-foundation.png" ],
  ["IPFS", "https://ipfs.io", "./teams/ipfs.jpeg" ],
  ["Spaceport", "", "./teams/spaceport.jpeg" ],
  ["PL Launchpad", "https://pl-launchpad.io", "./teams/pl-launchpad.png" ],
  ["LibP2P", "", "./teams/libp2p.png" ],
  ["Drand", "", "./teams/drand.png" ],
  ["Lotus", "", "./teams/lotus.jpeg" ],
  ["Compute Over Data", "", "./teams/compute-over-data.png" ],
  ["Talent Protocol", "", "./teams/talent-protocol.png" ],
]

# this is a Frequently Asked Questions section.
#
# the format is:
# "Question here?" = """
# Answer here at length.
# """
[faq]
"What is IPFS Camp 2022?" = """
IPFS Camp 2022 is a gathering for the entire IPFS community: builders, operators, researchers… and you! There will be talks, workshops, discussion circles, hacking time, and more — all focused on celebrating and advancing IPFS. 
"""
"Who is it for? Why should I attend?" = """
IPFS Camp is for everyone who would like to build the Distributed Web together. The 3-day event is designed for a broad range of interests and experience via multiple, parallel tracks. You can expect to…
 - Meet IPFS creators, maintainers, builders & operators
 - Learn about progress & plans for IPFS & libp2p
 - Join discussions and workshops on key goals and challenges
 - Share your work in building the Distributed Web
 - Learn how you can contribute to IPFS & grow your own IPFS-based projects
"""
"Sounds great! How do I participate?" = """
If you don’t have a ticket yet, head to the Tickets section to purchase a ticket or apply for a discounted one.

This is a decentralized event, with over 15 tracks across 3 days. Explore the track descriptions and schedules, and choose your own adventures depending on your interests! 

We’re keen to showcase builders, users, and ideas from across the community. If you’re interested in giving a talk, sharing your work, or leading a new track, please Apply to Speak.
"""    
"What does the ticket include?" = """
All tickets include entry to the full 3-day event and coffee, pastries, lunch, and dinner at the IPFS Camp venue. 
"""
"Can I organize a side event?" = """    
Yes! Please reach out to camp@ipfs.io if you’d like to discuss listing it on this website.
"""    
"What's the COVID policy?" = """    
It has been almost three years since our last in-person IPFS Camp! We’re excited to see everyone’s faces soon! While COVID-19’s most acute days are past, we are taking precautions to help limit spread and protect the health of our IPFS and global communities.
As of September 2022, Portugal has lifted entry requirements related to COVID-19.

RAPID ANTIGEN TESTING: IPFS Camp will host a 100% free mobile testing site at the entrance to Convento do Beato where every attendee will be required to take an antigen rapid test prior to picking up their badge (regardless of vaccination status).
Tests will be self administered, and results take about 15 minutes to process. 

MASKS: IPFS Camp will have plenty of masks and hand sanitizer available at the entrance and key locations within the venue each day. We recommend wearing a mask indoors.

MEALS: Lunch and dinner will primarily take place in well-ventilated areas or outdoors.

ILLNESS: If you feel sick or have tested positive, stay at home. If at any point during your visit to IPFS Camp you feel sick, please visit our onsite testing center to take a follow-up test. Whether or not you test positive for COVID-19, if you have symptoms that mirror any other communicable disease (i.e. flu, cold, etc.) we ask that you do not visit in-person venues until your symptoms subside. 

If you must cut short your visit to IPFS Camp due to illness, you may email camp@ipfs.io for a ticket refund. We will be sorry to see you go but thankful for your part in keeping the community healthy.
"""
"How do I reach the organizers?" = """    
Please reach out to camp@ipfs.io with any questions or suggestions.
"""

# Speaker Items
#
# the format is:
# [[speakers]]
# name = "Speaker Name"
# company = "Company"
# image = "image.jpg"

[[speakers]]
name = "Ruben Amenyogbo"
company = "Protocol Labs"
image = "speakers/ruben-amenyogbo.jpg"
[[speakers]]
name = "Dietrich Ayala"
company = "Protocol Labs"
twitterProfile="dietrich"
image = "speakers/dietrich-ayala.jpg"
[[speakers]]
name = "Juan Benet"
company = "Protocol Labs"
twitterProfile="juanbenet"
image = "speakers/juan-benet.jpg"
[[speakers]]
name = "Tanguy Cizain"
company = "Status.im"
image = "speakers/tanguy-cizain.jpg"
[[speakers]]
name = "Carson Farmer"
company = "Textile"
twitterProfile="carsonfarmer"
image = "speakers/carson-farmer.jpg"
[[speakers]]
name = "Sara Feenan"
company = "Infura"
twitterProfile="saronimo"
image = "speakers/sara-feenan.jpg"
[[speakers]]
name = "Wes Floyd"
company = "Protocol Labs"
twitterProfile="weswfloyd"
image = "speakers/wes-floyd.jpg"
[[speakers]]
name = "Hannah Howard"
company = "Protocol Labs"
twitterProfile="techgirlwonder"
image = "speakers/hannah-howard.jpg"
[[speakers]]
name = "Michelle Lee"
company = "Protocol Labs"
twitterProfile="mishmosh"
image = "speakers/michelle_lee.jpg"
[[speakers]]
name = "Molly Mackinlay"
company = "Protocol Labs"
twitterProfile="momack28"
image = "speakers/molly-mackinlay.jpg"
[[speakers]]
name = "Boris Mann"
company = "FISSION"
twitterProfile="bmann"
image = "speakers/boris-mann.jpg"
[[speakers]]
name = "Mauve Signweaver"
company = "Agregore Browser"
twitterProfile="RangerMauve"
image = "speakers/mauve-signweaver.jpg"
[[speakers]]
name = "Cayman Nava"
company = "ChainSafe Systems"
twitterProfile="caymannan"
image = "speakers/cayman-nava.jpg"
[[speakers]]
name = "Brendan O'Brien"
company = "Number Zero"
twitterProfile="b_fiive"
image = "speakers/brendan-obrien.jpg"
[[speakers]]
name = "Camila Ramos"
company = "Fuel Labs, Women Build Web 3"
twitterProfile="camiinthisthang"
image = "speakers/camila-ramos.jpg"
[[speakers]]
name = "Marcin Rataj"
company = "Protocol Labs"
twitterProfile="lidelOrg"
image = "speakers/marcin-rataj.jpg"
[[speakers]]
name = "Niklas Rindtorff"
company = "LabDAO"
twitterProfile="Niklas_TR"
image = "speakers/niklas-rindtorff.jpg"
[[speakers]]
name = "Brooklyn Zelenka"
company = "FISSION"
twitterProfile="expede"
image = "speakers/brooklyn-zelenka.jpg"
[[speakers]]
name = "Alex Potsides"
company = "Protocol Labs"
twitterProfile="achingbrain"
image = "speakers/alex-potsides.jpg"
[[speakers]]
name = "Gorka Ludlow"
twitterProfile="AquiGorka"
company = "Gather"
image = "speakers/gorka-ludlow.jpg"
[[speakers]]
name = "Horacio Herrera"
company = "Mintter"
twitterProfile="hhg2288"
image = "speakers/horacio-herrera.jpg"
[[speakers]]
name = "Chris Anderson"
company = "DAG House"
twitterProfile="jchris"
image = "speakers/chris-anderson.jpg"
[[speakers]]
name = "Hector Sanjuan"
company = "Protocol Labs"
twitterProfile="hecturchi"
image = "speakers/hector-sanjuan.jpg"
[[speakers]]
name = "Manfred Touron"
company = "Berty Technologies"
twitterProfile="moul"
image = "speakers/manfred-touron.jpg"
[[speakers]]
name = "Rüdiger Klaehn"
company = "Independent Software Engineer"
image = "speakers/rudiger-klaehn.jpg"
[[speakers]]
name = "Daniel Norman"
twitterProfile="daniel2color"
company = "Protocol Labs"
image = "speakers/daniel-norman.jpg"
[[speakers]]
name = "Matt Ober"
company = "Pinata"
image = "speakers/matt-ober.jpg"
[[speakers]]
name = "Thibault Muenier"
company = "Cloudflare"
image = "speakers/thibault-muenier.png"
[[speakers]]
name = "Alan Shaw"
company = "Protocol Labs"
image = "speakers/alan-shaw.png"
[[speakers]]
name = "Oleg Silkin"
company = "Red Hat"
image = "speakers/oleg-silkin.jpg"
[[speakers]]
name = "Pasquale Sorrentino"
company = "Gummys.io"
image = "speakers/pasquale-sorrentino.png"


# Ticket Items
#
# [[tickets]]
# name = "General"
# price = "($400)"
# description = "The essential ticket for attending IPFS Camp 2022. This is for everyone!"
# linkLabel = "Purchase General Ticket"
# link = "#"

[[tickets]]
name = "General"
price = "($400)"
description = "The essential ticket for attending IPFS Camp 2022. This is for everyone!"
linkLabel = "Purchase General Ticket"
link = "https://lu.ma/ipfscamp22"
[[tickets]]
name = "Builder"
price = "($200)"
description = "Discounted tickets for builders: anyone who is building with IPFS or related technologies, or contributing to IPFS project or community."
linkLabel = "Purchase Builder Ticket"
link = "https://lu.ma/ipfscamp22_builders"
[[tickets]]
name = "Student & Academic"
price = "($100)"
description = "Limited tickets for students, educators and researchers with academic affiliation and experience or interest in IPFS."
linkLabel = "Apply for Academic Ticket"
link = "https://airtable.com/shrBS3hLqKlnakxHB"
[[tickets]]
name = "Volunteer"
price = "(Free)"
description = "Limited tickets for community members who can volunteer for 3 x 2 hour shifts during the event."
linkLabel = "Apply for Volunteer Ticket"
link = "https://airtable.com/shrum6nLOI23vwIcJ"
[[tickets]]
name = "IPFS Scholars"
price = "(Free)"
description = "This program provides entry, flights, and accommodation for individuals from underrepresented communities, unique circumstances, or developing areas to connect with and contribute to the IPFS ecosystem."
linkLabel = "Sold Out!"
link = "https://airtable.com/shrd4kSljHYHxmU1b"

# Tracks Section
# Hide propose button by commenting out
#
[tracksSection]
title="Tracks"
proposeLink="https://airtable.com/shrBQqf7YJRPdrgUo"
proposeLabel="Propose a Track"

# schedule section
[schedule]
description="""
Choose your own adventure from over 16 tracks across 3 days. 
"""
