# the name of your track or event
name = "Compute Over Data (Madrui Room)"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Eric Myhre, David Aronchik"

# the start date of the event
date = "2022-10-29"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00 - 13:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  Producing data without leaving the Merkle Forest — How do we do it? How do we make it manageable at scale? 
  How do we make the results useful and discoverable? In this track, see what others are up to, and share your own dreams!
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 13:00 (Day 1 is 10-12 keynotes, 12-13 lunch)
# - recommended end:   17:00, you can run to 18:00 if needed
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="10:00"
speakers=["David Aronchik, Wes Floyd"]
title="Keynote & Overview Survey"
description=""

[[timeslots]]
startTime="10:30"
speakers=["Eric Evenchick"]
title="Warpforge — Hashes go in, hashes come out, exec in the middle!"
description=""

[[timeslots]]
startTime="11:00"
speakers=["David Aronchik", "Wes Floyd"]
title="Bacalhau — Bringing the Compute to the Data!"
description=""

[[timeslots]]
startTime="11:30"
speakers=["@warpfork"]
title="Zapps — A new standard for go-anywhere linux executables"
description=""

[[timeslots]]
startTime="12:00"
speakers=["Matt Hamilton"]
title="FVM -- The (EVM-Compatible!) Filecoin Virtual Machine"
description=""

[[timeslots]]
startTime="12:30"
speakers=["@warpfork"]
title="Solving the One Hard Problem — Naming Things — With Catalogs"
description=""

[[timeslots]]
startTime="13:00"
speakers=[]
title="Lunch Break"
description=""

