# the name of your track or event
name = "Content Routing"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Will Scott"

# the start date of the event
date = "2022-10-29"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00 - 13:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "Intermediate"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops", "Panels"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  Approaches and protocols to content routing in IPFS, what we've learned so far, and directions for the future.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 10:00
# - recommended lunch: 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="09:00"
speakers=[]
title="Arrival / Breakfast"
description=""

[[timeslots]]
startTime="10:00"
speakers=["@willscott"]
title="Track Intro"
description=""

[[timeslots]]
startTime="10:15"
speakers=["@masih", "@guseggert", "@ajnavarro"]
title="State of Content Routing"
description="What's going on with DHTs, hydras, indexers, and reframe"

[[timeslots]]
startTime="10:45"
speakers=["@gammazero"]
title="Scaling content routing"
description="How many CIDs are there, and what are the open scaling questions in content routing?"

[[timeslots]]
startTime="11:00"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="11:15"
speakers=["@ischasny"]
title="Workshop: Indexed content routing"
description="Explore Kubo delegated routing to publish and query indexers"

[[timeslots]]
startTime="11:45"
speakers=["@thibmeu"]
title="Where's bafy: gateway perspective on content routing"
description="Content routing from a Gateway's perspective"


[[timeslots]]
startTime="12:00"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="12:15"
speakers=["@elijaharita"]
title="Keeping Estuary Content Available"
description="How Estuary keeps content available today and in the future"


[[timeslots]]
startTime="12:30"
speakers=["@guseggert", "@willscott", "@alanshaw"]
title="Panel: the future of content routing"
description="How could inter-planetary content routing continue to evolve going forward?"

[[timeslots]]
startTime="13:00"
speakers=[]
title="Lunch Break"
description=""
