# the name of your track or event
name = "Decentralized Job Fair"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Jeremy Kloth"

# the start date of the event
date = "2022-10-29"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "17:00 - 19:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Job Fair"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  Whether you are looking for a new role, hiring for your project, or simply want to learn more about 
  open source projects that you can contribute to, the Decentralized Job Fair is for you.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
