# the name of your track or event
name = "IPFS Operators and Enterprise"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Cory Schwartz"

# the start date of the event
date = "2022-10-29"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00 - 17:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  Explore applications & deployments of IPFS in large scale cloud & 
  enterprise use cases, with talks from IPFS operators about their experiences and best practices.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 10:00
# - recommended lunch: 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="09:50"
speakers=["Cory Schwartz"]
title="Track Introduction"
description="Welcome!"

[[timeslots]]
startTime="10:00"
speakers=["Sara Freenan (Consensys)"]
title="Build the web we want"
description="""
Recently, we deprecated our public gateway and it came to light that creators
had been using our public gateway url, along with the CID, in their NFT
metadata, instead of using the CID. 

I would like to take this opportunity to remind people that IPFS is about building
a decentralised web that is not beholden to one company or organisation. CIDs are
content identifiers, not resource locators. The beauty of the protocol is that the
content can be found on the network using the CID via the cooperation of the node
providers, and the built in redundancy of the protocol. 

The decentralised and resilient web we want will rely on people embedding these new
patterns into whatever they create and build on top of the protocol and we at Infura
want to help in whatever way we can.
"""

[[timeslots]]
startTime="10:35"
speakers=[]
title="break"

[[timeslots]]
startTime="10:40"
speakers=["Matt Ober (Pinata)"]
title="Protecting IPFS gateways at scale"
description="""
IPFS gateways are an important portal into the IPFS network, but running publicly
accessible IPFS gateways comes with great risk and responsibility. In this talk Matt
will discuss common challenges that IPFS gateway operators will encounter and how
Pinata has solved for them.
"""

[[timeslots]]
startTime="11:15"
speakers=[]
title="break"
description=""

[[timeslots]]
startTime="11:20"
speakers=["Thibault Meunier (Cloudflare)"]
title="Secure your IPFS website"
description="""
For wallets, decentralized exchanges, DeFi insurer, or DAO management, most IPFS
applications are relying on HTTP. This setup allows applications to be accessible by
current web users, with minimal modifications. It also enables developers to leverage
common web engineering practice. However, these HTTP endpoints have to be secured, and
trust provided by the decentralized-network has to be carried to end-users. HTTPS is
not enough. This talk will present the setup of a browser based IPFS app.
"""

[[timeslots]]
startTime="11:55"
speakers=[]
title="break"
description=""

[[timeslots]]
startTime="12:00"
speakers=["Mario Camou (Protocol Labs)"]
title="IPFS gateway"
description="""
Words of the wise. On growing and building one of the busiest IPFS gateways in the world.
"""

[[timeslots]]
startTime="12:40"
speakers=["Mahmoud Shehata (fleek)"]
title="Fleek Network - Decentralized Content and Application Delivery Network"
description=""

[[timeslots]]
startTime="13:00"
speakers=[]
title="Lunch"
description=""


[[timeslots]]
startTime="14:00"
speakers=["Ansgar Grunseid (saturn)"]
title="Introducing Saturn, web3 CDN"
description="""
Saturn is a Web3 CDN in Filecoin's retrieval market built with IPFS-addressable data.
"""

[[timeslots]]
startTime="14:35"
speakers=[]
title="break"
description=""

[[timeslots]]
startTime="14:40"
speakers=["Héctor Sanjuán (Protocol Labs)"]
title="Pinset orchestration with IPFS Cluster"
description="""
IPFS Cluster makes distributing a pinset across an scalable set of Kubo peers easy.
In this talk, we will explore the basic features, setup and monitoring for home and
production deployments.
"""

[[timeslots]]
startTime="15:15"
speakers=[]
title="break"
description=""

[[timeslots]]
startTime="15:20"
speakers=["Oleg Silkin (Red Hat)"]
title="What Kubernetes Operators Do That Regular Deployments Do Not"
description="""
By the end of this talk  users will know how Kubernetes Operators can improve their
experience with deploying large-scale applications in their clusters. Attendees will
also learn how IPFS Cluster leverages the Operator SDK in order to easily perform
horizontal scaling of Web3 storage. 
"""

[[timeslots]]
startTime="15:55"
speakers=[]
title="break"
description=""

[[timeslots]]
startTime="16:00"
speakers=["Alan Shaw (Protocol Labs)"]
title="Elastic IPFS -- The scales are off the charts!"
description="""
What even is Elastic IPFS and how much stretch does it have? THIS is the story of the
brand new multi tenant IPFS implementation that runs in the cloud, separates read and
write pipelines to really, truly achieve web scale beyond anything this world has even
seen before.
"""

[[timeslots]]
startTime="16:35"
speakers=[]
title="break"
description=""

[[timeslots]]
startTime="16:40"
speakers=[]
title="IPFS Service Panel"
description="""
Panel discussion of gateway operators, pinning services, and others who operate IPFS
services.
"""
# Still recruiting people to join this panel.
# Panel members:
# * Thibault Munier
# * Jay Graber
# * ~bifrost
