# the name of your track or event
name = "IPFS 101 / User Apps on IPFS (decentralise all the things!) (Arion Room)"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "DeveloperAlly"

# the start date of the event
date = "2022-10-28"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "13:00 - 17:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "Beginner"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops", "Demos"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  This packed track will include both 1.5 hours of Learning IPFS 101 & Talks from User Apps 
  built on IPFS to help spark your own ideas.
  
  Learn IPFS 101 is a hands on session on getting started with IPFS, including what it 
  is, how to set up an IPFS node, CLI commands, pinning, gateways and more. 
  If you've been wanting to try out IPFS - now's your chance!
  
  User Apps on IPFS focusses on the awesome decentralised apps that have been built on top of the IPFS
  protocol including Livepeer, Fleek, Peeranha, Huddle01 and more. Come and discover new apps you can use to 
  decentralise your data life.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="13:00"
speakers=["Ryan Baumann"]
title="Breaking Free of the Client-Server Model with IPFS"
description="An Introduction to IPFS, its key features and benefits"

[[timeslots]]
startTime="13:30"
speakers=["Lindsay Walker"]
title="Hands On with IPFS - Installing, using the CLI and implementing kubo in a boilerplate app"
description="Lindsay Walker will lead a hands-on workshop to help you get up and running with IPFS"

[[timeslots]]
startTime="14:30"
speakers=["Max Boytsov"]
title="Fleek XYZ + IPFS Storage plugin Workshop"
description="1. We’ll write a skeleton with dummy modules for IPFS Storage Plugin
2. We’ll start to fulfil the plugin, starting from its metadata and ending all the different methods being written with an SDK
3. Once the plugin file is finished, we’ll build the plugin library for it and import it into the fleek-xyz GraphQL module.
4. We’ll go to the Fleek.xyz UI to show:
    1. How the newly created plugin is displayed in the list of storage plugins 
    2. How we’re initializing that plugin."

[[timeslots]]
startTime="15:00"
speakers=["Shannon Wells"]
title="Building the Future of Web3 Video Applications With Livepeer"
description="Building the future of web3 video applications is a difficult feat. Livepeer makes it easy!"

[[timeslots]]
startTime="15:30"
speakers=["Sergey Llin"]
title="Peeranha: Organisation of knowledge in Web3"
description="Information in Web3 is spread across fragmented communities in Discord, Slack and Telegram channels. That information is not exposed to Google search, hard to find, unstructured and not curated.
And we have created a solution!
Peeranha streamlines knowledge management & discovery in Web3, creates incentives for users to contribute, gives ownership of the knowledge back to the community and preserves it by storing on Polygon blockchain and Filecoin."

[[timeslots]]
startTime="15:55"
speakers=["Steph Orpilla"]
title="Building YourCycle, a period tracking dapp powered by IPFS"
description="Over the next month, Steph is building YourCycle, a self-sovereign mobile period tracking dapp in public. Users encrypt their cycle data with public-key encryption, then store it in an Orbit DB feed on IPFS."

[[timeslots]]
startTime="16:15"
speakers=["Logan Lentz", "Alex Mirran"]
title="Openlinks - web3 Linktree"
description="Why microsites on IPFS make seense and considering trade-offs and how those decisions affect IPFS in your applications."

[[timeslots]]
startTime="16:25"
speakers=["Ryan Shahine"]
title="Portrait.gg - decentralised websites on IPFS"
description="During this talk Ryan will give a deep-dive into how Portrait leverages IPFS and an on-chain registry to store and govern decentralized websites and how transferable DAOs may be established easily without coding experience."

[[timeslots]]
startTime="16:35"
speakers=["Dave Montali"]
title="NIMI.eth - Web3 Social powered by IPFS"
description="Nimi is a social aggregator, which allows users to effortlessly host on their ENS domains - powered by IPFS in the background. From hackathon to thousands of users we grew with IPFS and took a journey through the ecosystem. Today Nimi users have IPNS keys set on their ENS domains, allowing them to update their Nimi profiles without transaction fees. "

[[timeslots]]
startTime="16:45"
speakers=["Konrad Urban"]
title="Endless Jewellery: How IPFS can store memories in gold"
description="Jewelry, but with a letter salad: NFC IOT NFT IPFS. How does it all fit together? Store memories and messages forever with IPFS. Record a voice message, which gets minted as an NFT that's stored on IPFS. The link is then put onto an NFC chip that's inside a physical piece of jewellery. This way, every time you tap your phone, you can see this message."

[[timeslots]]
startTime="16:50"
speakers=["Chris Anderson"]
title="NFT.Storage - NFTUp"
description="Upload files and directories with NFTUp!"

[[timeslots]]
startTime="16:55"
speakers=["Ally Haire"]
title="Wrap up"
description="Quick wrap up before the Project Expo!"
