# the name of your track or event
name = "IPFS Implementations"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "b5"

# the start date of the event
date = "2022-10-28"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "13:00 - 17:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  Are you looking to choose the right IPFS implementation to build on? Do you want to find an IPFS implementation to _work_ on? This track aims to answer both.
  
  Meet the teams taking IPFS to the next level. Find an implementation that you can bet your project on, or if you dare, let yourself be nerd sniped into working on the protocol itself.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 13:00 (Day 1 is 10-12 keynotes, 12-13 lunch)
# - recommended end:   17:00, you can run to 18:00 if needed
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="13:00"
speakers=["Brendan O'Brien (@b5)"]
title="Interplanetary Cambrian Explosion"
description="""
A wave of new IPFS implementations has grown in the past year. This track introduction will give an overview of recent developments in IPFS implementations, and how existing ones are adapting to meet new demands. 
"""

[[timeslots]]
startTime="13:15"
speakers=["Alan Shaw"]
title="IPFS at scale"
description="Alan's talk will give a high level overview of infrastructure the DAG House team has built for serving massive amounts of IPFS content to thousands of users around the world."

[[timeslots]]
startTime="13:30"
speakers=["Marcin Rataj (@lidel)"]
title="Improving IPFS specifications"
description="Significant progress is being made around spec coverage and improvement proposal (IPIP) process. Where we go from here?"

[[timeslots]]
startTime="14:00"
speakers=["RÃ¼diger Klaehn"]
title="A new approach to IPFS pinning and caching"
description="""
Ipfs-Embed is a small embeddable version of a subset of IPFS, written in rust. It is used in production in the German manufacturing industry.

This talk will present a novel API for pinning, caching and garbage collection that is designed for the use case of highly interactive and dynamic applications with soft real time requirements.

Afterwards there will be a discussion about advantages and disadvantages of this approach, and how it compares to the Kubo API.
"""

[[timeslots]]
startTime="14:20"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="14:30"
speakers=["Guss Eggart"]
title="State of Kubo"
description="[Kubo](https://github.com/ipfs/kubo) (formerly go-ipfs) is the reference implementation for the protocol, and drives the vast majority of IPFS traffic. Hear where Kubo is headed next."

[[timeslots]]
startTime="14:45"
speakers=["Alex Potsides (@achingbrain)"]
title="State of IPFS-in-JS"
description="Alex will walk us through where [IPFS-in-JS](https://js.ipfs.tech/) is headed in 2023."

[[timeslots]]
startTime="15:00"
speakers=["Jacob Heun"]
title="Bitswap in Boost - IPFS retrieval from Filecoin"
description="Jacob will demonstrate an incredible new technique for bridging Filecoin content directly into IPFS"

[[timeslots]]
startTime="15:30"
speakers=["Paolo Insogna"]
title="Horizontal Scaling of a Web3 system to the sky and beyond in AWS"
description="Paolo will walk us through [Elastic IPFS](https://github.com/elastic-ipfs/elastic-ipfs)"

[[timeslots]]
startTime="16:00"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="14:15"
speakers=["Kasey Huizinga (@ramfox)"]
title="Iroh: Efficient IPFS in Rust"
description="""
[Iroh](https://iroh.computer) is a next-generation implementation of IPFS. It's a ground-up rethink of what IPFS can be, written in Rust by IPFS community veterans.

Kasey's talk will walk us through the first release of iroh, how you can use it, and where the project is headed.
"""

[[timeslots]]
startTime="16:15"
speakers=["Jeff Thompson"]
title="Gomobile IPFS"
description="""
Jeff will walk us through [gomobile IPFS](https://github.com/ipfs-shipyard/gomobile-ipfs), a set of packages for Android, iOS and React-Native that allow one to run and use an IPFS node on mobile devices. 
"""

