# the name of your track or event
name = "Keynotes"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
# dri = "Mosh Lee"

# the start date of the event
date = "2022-10-28"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00 - 12:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Panels"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = "A warm and wonderful kickoff to IPFS Camp with keynote speakers, fireside chats, and a sampling of community talks and community perspectives on the present and future of IPFS."

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon

startTime="10:00"
speakers="Mosh Lee and Dietrich Ayala"
title="Welcome"

startTime="10:05"
speakers="Molly Mackinlay"
title="State of IPFS Ecosystem"
description="Short overview of the state of the IPFS world by the numbers, highlighting the major events or phases since IPFS Camp 2019."

startTime="10:15"
speakers="Jay Graber (Bluesky), Manos Nikiforakis (WeatherXM), Francis Tyers (Omnilingo)"
title="IPFS Applications Showcase"
description="Three IPFS applications show off what they've built and share the critical needs the protocol and implementations must deliver on in order to succeed."

startTime="10:30"
speakers="Jonathan Dotan (Starling), Phoebe Poon (Liker Land), Xavi Vives (Vocdoni)"
title="Decentralization and Human Rights Showcase"
description="Three projects that use IPFS to improve information access & preservation to benefit human knowledge and human rights."

startTime="10:50"
speakers="Juan Benet, Gus Eggert, Brendan O'Brien, Alan Shaw, Alex Potsides"
title="IPFS Implementations"
description="Lightning talks from the creator of IPFS and the lead maintainers of key IPFS implementations on the current state and future of each, followed by a short panel discussion on what's needed most and the challenges of implementation and maintainership."

startTime="11:25"
speakers="Juan Benet, Mosh Lee, Dietrich Ayala"
title="IPFS Fund Announcement"
description="Learn about a new funding effort to expand IPFS implementations into new and different areas and support broad ecosystem initiatives such as education, developer tooling and more."

startTime="11:35"
speakers="All track leads"
title="Track-o-Rama"
description="With over 15 tracks and a choose-your-own adventure format, how will you choose? In this session, track leads will give a 60-second pitch for why EVERYONE should come to their track."

startTime="11:55"
speakers="Harry Yeff"
title="Voice Gems: A 1000 Year Archive"
description="In 2020 Harry Yeff and Trung Bao set out to preserve a set of human voices for 1000 years, a feat that evokes many challenges and questions. In this talk & performance, artist and technologist Harry Yeff (Reeps100) showcases his portfolio of speed-of-light radio transmission, AI synthetic voices and how emerging technologies provide an artistically explosive and vital discussion on new methods of preservation."
