# the name of your track or event
name = "Libp2p Day (Saffar Room)"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Marco Munizaga, Prithvi Shahi"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://discuss.libp2p.io/t/first-ever-libp2p-day-oct-30-lisbon-portugal/1582"

# the start date of the event
date = "2022-10-30"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00 - 17:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops", "Unconference"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  The first ever libp2p Day: a gathering for libp2p builders, contributors, and maintainers!
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 10:00
# - recommended lunch: 13:00
# - recommended end:   16:00 (On 30 Oct, 1h Camp wrapup begins at 16:00)
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon

[[timeslots]]
startTime="10:00"
speakers=["Marco Munizaga"]
title="Intro to libp2p: helping with real world application problems"
description=""

[[timeslots]]
startTime="10:25"
speakers=["Steve Loeppky"]
title="A month in PL EngRes libp2p Development and how you can be involved"
description=""

[[timeslots]]
startTime="10:45"
speakers=["Marten Seemann"]
title="Browser connectivity state of the union and demo"
description=""

[[timeslots]]
startTime="11:15"
speakers=["Ryan Plauche & Max Inden"]
title="Why WebRTC"
description=""

[[timeslots]]
startTime="11:35"
speakers=["Dennis Trautwein"]
title="libp2p NAT Hole Punching"
description=""

[[timeslots]]
startTime="12:10"
speakers=["Tanguy Cizain"]
title="libp2p in Nim"
description=""

[[timeslots]]
startTime="12:35"
speakers=["Laurent Senta"]
title="Testground + libp2p"
description=""

[[timeslots]]
startTime="13:00"
speakers=[]
title="Lunch Break"
description=""

[[timeslots]]
startTime="14:00"
speakers=["Cayman Nava"]
title="Intro to Lodestar"
description=""

[[timeslots]]
startTime="14:20"
speakers=["Gorka Ludlow"]
title="WebRTC signalling data over QR codes"
description=""

[[timeslots]]
startTime="14:40"
speakers=["Ankit Kumar"]
title="Formal Analysis of GossipSub"
description=""

[[timeslots]]
startTime="15:00"
speakers=["Elliott Frisch"]
title="How Pyrsia is using libp2p to take over the world"
description=""

[[timeslots]]
startTime="15:20"
speakers=["Max Inden"]
title="DOS defense - do’s and dont’s"
description=""

[[timeslots]]
startTime="15:40"
speakers=[""]
title="Open Unconf Slot"
description=""

[[timeslots]]
startTime="16:00"
speakers=["Petar Maymounkov"]
title="The power of two choices – Why the Kademlia binary tree isn’t balanced and what we can do about it"
description=""

[[timeslots]]
startTime="16:20"
speakers=[""]
title="Open Unconf Slot"
description=""

[[timeslots]]
startTime="16:40"
speakers=[""]
title="Open Unconf Slot"
description=""

