# the name of your track or event
name = "Lightning Talks Session 1"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Reid Wilkes"

# the start date of the event
date = "2022-10-30"

# how many days the event lasts (1 - N)
days = 1

venueName = "Madriu"

# the event times (shows up in the event card)
times = "10:00 - 13:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  Come hear a fantastic lineup of 15-minute talks covering all kinds of juicy IPFS related topics! 
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="10:15"
speakers=["Techie Teee"]
title="Data for Degens"
description=""

[[timeslots]]
startTime="10:30"
speakers=["Xavi Vives"]
title="Trancending natural language"
description=""

[[timeslots]]
startTime="10:45"
speakers=["Hugo Montenegro"]
title="Unstoppable Frontends with IPFS - Cybersquirrel Case Study"
description=""

[[timeslots]]
startTime="11:00"
speakers=["Moritz Schubotz"]
title="What if the European Open Science Cloud ran on libp2p?"
description=""

[[timeslots]]
startTime="11:15"
speakers=["Coffee Break"]
title=""
description=""

[[timeslots]]
startTime="11:30"
speakers=["Edward Silverton"]
title="NIIIFTY: Data Reliability for the Cultural Heritage Sector using IPFS"
description=""

[[timeslots]]
startTime="11:45"
speakers=["Alex Wilhelm"]
title="Compose DB - Composable Data on Ceramic"
description=""